# Generated by Django 4.2.1 on 2024-11-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyexchangerates',
            old_name='rate',
            new_name='exchange_rate',
        ),
    ]
