# Generated by Django 4.2.1 on 2024-11-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_rate_currencyexchangerates_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='currencyexchangerates',
            name='base',
            field=models.CharField(max_length=3, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency')),
        ),
        migrations.AlterField(
            model_name='currencyexchangerates',
            name='target',
            field=models.CharField(max_length=3, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency')),
        ),
    ]
