# Generated by Django 4.2.1 on 2024-11-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_currency_alter_currencyexchangerates_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerates',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='api.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerates',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='api.currency'),
        ),
    ]
